-- DROP TABLE portal.visits;

CREATE TABLE portal.visits (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address varchar(45) NULL,
    country varchar(100) NULL,
    city varchar(100) NULL,
    region varchar(100) NULL,
    page varchar(200) NULL,
    user_agent text NULL,
    accessed_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
    referer text NULL,
    visit_type varchar(30) NULL,
    bot_name varchar(100) NULL,

    CONSTRAINT visits_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE portal.visits IS
    'Stores visitor telemetry collected by the portal.';

COMMENT ON COLUMN portal.visits.id IS
    'Unique identifier of the visit record.';

COMMENT ON COLUMN portal.visits.ip_address IS
    'IP address of the visitor, supporting IPv4 and IPv6.';

COMMENT ON COLUMN portal.visits.country IS
    'Country estimated from the visitor IP address.';

COMMENT ON COLUMN portal.visits.city IS
    'City estimated from the visitor IP address.';

COMMENT ON COLUMN portal.visits.region IS
    'Region or state estimated from the visitor IP address.';

COMMENT ON COLUMN portal.visits.page IS
    'Portal page accessed by the visitor.';

COMMENT ON COLUMN portal.visits.user_agent IS
    'HTTP User-Agent reported by the visitor client.';

COMMENT ON COLUMN portal.visits.accessed_at IS
    'UTC timestamp when the visit was recorded.';

COMMENT ON COLUMN portal.visits.referer IS
    'HTTP Referer indicating the page or website that originated the navigation.';

COMMENT ON COLUMN portal.visits.visit_type IS
    'Classification of the visit, such as human, crawler, social_crawler, bot, or unknown.';

COMMENT ON COLUMN portal.visits.bot_name IS
    'Identified name of the crawler or bot, when applicable.';

CREATE INDEX idx_visits_accessed_at
    ON portal.visits (accessed_at DESC);

CREATE INDEX idx_visits_ip_address_accessed_at
    ON portal.visits (ip_address, accessed_at DESC);

CREATE INDEX idx_visits_visit_type_accessed_at
    ON portal.visits (visit_type, accessed_at DESC);