using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Caching.Memory;
using PortalIRibeiro.API.Entities;
using PortalIRibeiro.API.Infrastructure.Repositories.Interfaces;
using PortalIRibeiro.API.Infrastructure.Serialization;

namespace PortalIRibeiro.API.Features.Iris;

/// <summary>
/// Gera as respostas da Íris via API do Gemini. O currículo é carregado do
/// Postgres (com cache em memória) e combinado com as instruções de sistema.
/// Se o contexto não for carregado, retorna uma mensagem amigável.
/// </summary>
public class GeminiService(
    HttpClient httpClient,
    IConfiguration configuration,
    ILogger<GeminiService> logger,
    IMemoryCache cache,
    IParameterRepository parameterRepository)
{
    private static readonly TimeSpan ContextCacheTtl = TimeSpan.FromMinutes(15);

    private const string NoAccessMessage = "Não tenho acesso aos dados do Itamar nesse momento.";

    private readonly string apiKey = configuration["Gemini:ApiKey"]
        ?? throw new InvalidOperationException("A chave de API do Gemini ('Gemini:ApiKey') não foi configurada.");

    private readonly string geminiUrl = configuration["Gemini:BaseUrl"]
        ?? throw new InvalidOperationException("A URL base do Gemini ('Gemini:BaseUrl') não foi configurada.");

    private readonly string geminiFallbackUrl = configuration["Gemini:FallbackBaseUrl"]
        ?? configuration["Gemini:BaseUrl"]
        ?? throw new InvalidOperationException("A URL de fallback do Gemini ('Gemini:FallbackBaseUrl') não foi configurada.");

    private readonly string paramKey = configuration["IrisSettings:ParamKey"] ?? "curriculo:itamar";

    private readonly string systemInstruction = LoadInstructions(logger);

    /// <summary>
    /// Carrega as instruções da Íris do arquivo iris_instruction.md.
    /// </summary>
    /// <param name="log">Logger usado para registrar o resultado da carga.</param>
    /// <returns>Conteúdo das instruções, ou um texto padrão quando o arquivo não existe.</returns>
    private static string LoadInstructions(ILogger<GeminiService> log)
    {
        var contextPath = Path.Combine(AppContext.BaseDirectory,
            "Features",
            "Iris",
            "Context", "iris_instruction.md");

        if (File.Exists(contextPath))
        {
            var content = File.ReadAllText(contextPath, Encoding.UTF8);
            log.LogInformation("Iris system instructions loaded from the Context folder.");
            return content;
        }

        log.LogWarning("File iris_instruction.md not found at {Path}. Using inline fallback.", contextPath);
        return "Você é a Íris, a assistente inteligente do portfólio de Itamar da Silva Ribeiro Junior. Desenvolvida estritamente com .NET 10 e Blazor.";
    }

    /// <summary>
    /// Gera a resposta da Íris para a pergunta do usuário.
    /// </summary>
    /// <param name="userQuestion">Pergunta enviada pelo usuário.</param>
    /// <returns>
    /// Resposta gerada, ou a mensagem amigável quando o currículo não
    /// pode ser carregado do banco.
    /// </returns>
    public async Task<string> GenerateResponseAsync(string userQuestion)
    {
        string? ragContext;
        try
        {
            ragContext = await GetCurriculumContextAsync();
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to load the curriculum context from Postgres. Key: {Key}", paramKey);
            return NoAccessMessage;
        }

        if (string.IsNullOrWhiteSpace(ragContext))
        {
            logger.LogWarning("Curriculum context not found in Postgres. Key: {Key}", paramKey);
            return NoAccessMessage;
        }

        try
        {
            // Payload fortemente tipado para Native AOT
            var payload = new GeminiRequest
            {
                SystemInstruction = new GeminiSystemInstruction
                {
                    Parts = [new GeminiPart { Text = systemInstruction }]
                },
                Contents =
                [
                    new GeminiContent
                    {
                        Role = "user",
                        Parts = [new GeminiPart { Text = $"<rag_context>\n{ragContext}\n</rag_context>\n\n<user_input>\n{userQuestion}\n</user_input>" }]
                    }
                ]
            };

            // Serialização via Source Generator
            var jsonPayload = JsonSerializer.Serialize(payload, AppJsonContext.Default.GeminiRequest);

            // Tenta o modelo principal; em caso de falha, usa o secundário
            var primaryResult = await TryGenerateResponseAsync(geminiUrl, jsonPayload);
            if (!string.IsNullOrWhiteSpace(primaryResult))
            {
                logger.LogInformation("Answer generated by the primary Gemini model: {Model}.", ExtractModelName(geminiUrl));
                return primaryResult!;
            }

            logger.LogWarning("Primary model ({Model}) unavailable, trying the fallback model ({FallbackModel}).",
                ExtractModelName(geminiUrl), ExtractModelName(geminiFallbackUrl));
            var fallbackResult = await TryGenerateResponseAsync(geminiFallbackUrl, jsonPayload);

            if (!string.IsNullOrWhiteSpace(fallbackResult))
            {
                logger.LogInformation("Answer generated by the fallback Gemini model: {Model}.", ExtractModelName(geminiFallbackUrl));
                return fallbackResult!;
            }

            logger.LogError("Failed to get an answer from both the primary ({Model}) and fallback ({FallbackModel}) models.",
                ExtractModelName(geminiUrl), ExtractModelName(geminiFallbackUrl));
            return "Desculpe, estou com dificuldades para acessar meu cérebro de IA agora. Tente novamente em instantes.";
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Critical failure while communicating with the Gemini service.");
            return "Ocorreu um erro no meu sistema de processamento de linguagem.";
        }
    }

    /// <summary>
    /// Monta o contexto RAG a partir do currículo no Postgres, com cache
    /// em memória (TTL de 15 minutos).
    /// </summary>
    /// <returns>
    /// O contexto do currículo, ou <see langword="null"/> quando o parâmetro
    /// não existe. Lança erro quando o banco está inacessível.
    /// </returns>
    private async Task<string?> GetCurriculumContextAsync()
    {
        string cacheKey = $"iris:context:{paramKey}";

        if (cache.TryGetValue(cacheKey, out string? cachedContext) && !string.IsNullOrWhiteSpace(cachedContext))
        {
            return cachedContext;
        }

        Parameter? parameter = await parameterRepository.GetByKeyAsync(paramKey);
        if (parameter is null || string.IsNullOrWhiteSpace(parameter.ParamValue))
        {
            return null;
        }

        cache.Set(cacheKey, parameter.ParamValue, ContextCacheTtl);
        return parameter.ParamValue;
    }

    /// <summary>
    /// Chama a API do Gemini para a URL e payload informados, retornando o
    /// texto gerado. Respostas de erro retornam <see langword="null"/>.
    /// </summary>
    /// <param name="url">URL completa da chamada generateContent do modelo.</param>
    /// <param name="jsonPayload">Payload de requisição serializado.</param>
    /// <returns>Texto gerado, ou <see langword="null"/> em caso de falha.</returns>
    private async Task<string?> TryGenerateResponseAsync(string url, string jsonPayload)
    {
        var urlWithKey = $"{url}?key={apiKey}";
        var httpContent = new StringContent(jsonPayload, Encoding.UTF8, "application/json");

        try
        {
            using var httpResponse = await httpClient.PostAsync(urlWithKey, httpContent);

            if (!httpResponse.IsSuccessStatusCode)
            {
                var errorDetails = await httpResponse.Content.ReadAsStringAsync();
                logger.LogError("Error calling the Gemini API. URL: {Url}. Status: {Status}. Details: {Error}", url, httpResponse.StatusCode, errorDetails);
                return null;
            }

            // Desserialização via Source Generator
            var jsonResponse = await httpResponse.Content.ReadAsStringAsync();
            var geminiResult = JsonSerializer.Deserialize(jsonResponse, AppJsonContext.Default.GeminiResponse);
            var responseText = geminiResult?.Candidates?[0].Content?.Parts?[0].Text;

            return responseText?.Trim() ?? "Não consegui formular uma resposta adequada. Pode perguntar de outra forma?";
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "HTTP request to the Gemini API failed. URL: {Url}", url);
            return null;
        }
    }

    /// <summary>
    /// Extrai o nome do modelo de uma URL generateContent.
    /// </summary>
    /// <param name="url">URL do modelo contendo /models/[nome]:generateContent.</param>
    /// <returns>Nome do modelo, ou a URL completa quando não for possível extrair.</returns>
    private static string ExtractModelName(string url)
    {
        var marker = "/models/";
        var index = url.IndexOf(marker, StringComparison.Ordinal);
        if (index < 0) return url;

        var segment = url[(index + marker.Length)..];
        var end = segment.IndexOf(":generateContent", StringComparison.Ordinal);
        return end > 0 ? segment[..end] : segment;
    }
}

// ==============================================================================
// DTOs de Requisição (API Gemini)
// ==============================================================================
/// <summary>
/// Payload enviado à API generateContent do Gemini.
/// </summary>
public class GeminiRequest
{
    [JsonPropertyName("systemInstruction")]
    public GeminiSystemInstruction? SystemInstruction { get; set; }

    [JsonPropertyName("contents")]
    public GeminiContent[]? Contents { get; set; }
}

/// <summary>
/// Instruções de sistema de uma requisição Gemini.
/// </summary>
public class GeminiSystemInstruction
{
    [JsonPropertyName("parts")]
    public GeminiPart[]? Parts { get; set; }
}

/// <summary>
/// Mensagem (turno de conversa) enviada à API Gemini.
/// </summary>
public class GeminiContent
{
    [JsonPropertyName("role")]
    public string Role { get; set; } = "user";

    [JsonPropertyName("parts")]
    public GeminiPart[]? Parts { get; set; }
}

/// <summary>
/// Uma parte de texto de uma mensagem Gemini.
/// </summary>
public class GeminiPart
{
    [JsonPropertyName("text")]
    public string? Text { get; set; }
}

// ==============================================================================
// DTOs de Resposta (API Gemini)
// ==============================================================================
/// <summary>
/// Resposta recebida da API generateContent do Gemini.
/// </summary>
public class GeminiResponse
{
    [JsonPropertyName("candidates")]
    public Candidate[]? Candidates { get; set; }
}

/// <summary>
/// Resposta candidata retornada pela API Gemini.
/// </summary>
public class Candidate
{
    [JsonPropertyName("content")]
    public ContentNode? Content { get; set; }
}

/// <summary>
/// Conteúdo de um candidato Gemini.
/// </summary>
public class ContentNode
{
    [JsonPropertyName("parts")]
    public PartNode[]? Parts { get; set; }
}

/// <summary>
/// Parte de texto do conteúdo de um candidato Gemini.
/// </summary>
public class PartNode
{
    [JsonPropertyName("text")]
    public string? Text { get; set; }
}