using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Caching.Memory;
using PortalIRibeiro.API.Entities;
using PortalIRibeiro.API.Infrastructure.Repositories.Interfaces;
using PortalIRibeiro.API.Infrastructure.Serialization;

namespace PortalIRibeiro.API.Features.Iris;

/// <summary>
/// Interacts with the Gemini API to generate Iris' answers. The curriculum context
/// is loaded from Postgres (with an in-memory cache) and combined with the system
/// instructions into the model payload. When the context cannot be loaded, a
/// friendly message is returned instead of calling the API.
/// </summary>
public class GeminiService(
    HttpClient httpClient,
    IConfiguration configuration,
    ILogger<GeminiService> logger,
    IMemoryCache cache,
    IParameterRepository parameterRepository)
{
    private static readonly TimeSpan ContextCacheTtl = TimeSpan.FromMinutes(15);

    private const string NoAccessMessage = "Não tenho acesso aos dados do Itamar nesse momento.";

    private readonly string apiKey = configuration["Gemini:ApiKey"]
        ?? throw new InvalidOperationException("A chave de API do Gemini ('Gemini:ApiKey') não foi configurada.");

    private readonly string geminiUrl = configuration["Gemini:BaseUrl"]
        ?? throw new InvalidOperationException("A URL base do Gemini ('Gemini:BaseUrl') não foi configurada.");

    private readonly string geminiFallbackUrl = configuration["Gemini:FallbackBaseUrl"]
        ?? configuration["Gemini:BaseUrl"]
        ?? throw new InvalidOperationException("A URL de fallback do Gemini ('Gemini:FallbackBaseUrl') não foi configurada.");

    private readonly string paramKey = configuration["IrisSettings:ParamKey"] ?? "curriculo:itamar";

    private readonly string systemInstruction = LoadInstructions(logger);

    /// <summary>
    /// Loads the Iris system instructions from the iris_instruction.md file.
    /// </summary>
    /// <param name="log">Logger used to trace the load result.</param>
    /// <returns>The instructions content, or an inline fallback when the file is missing.</returns>
    private static string LoadInstructions(ILogger<GeminiService> log)
    {
        var contextPath = Path.Combine(AppContext.BaseDirectory,
            "Features",
            "Iris",
            "Context", "iris_instruction.md");

        if (File.Exists(contextPath))
        {
            var content = File.ReadAllText(contextPath, Encoding.UTF8);
            log.LogInformation("Iris system instructions loaded from the Context folder.");
            return content;
        }

        log.LogWarning("File iris_instruction.md not found at {Path}. Using inline fallback.", contextPath);
        return "Você é a Íris, a assistente inteligente do portfólio de Itamar da Silva Ribeiro Junior. Desenvolvida estritamente com .NET 10 e Blazor.";
    }

    /// <summary>
    /// Generates Iris' answer for the given user question.
    /// </summary>
    /// <param name="userQuestion">The user's question sent to Iris.</param>
    /// <returns>
    /// The generated answer, or the friendly message when the curriculum context
    /// cannot be loaded from the database.
    /// </returns>
    public async Task<string> GenerateResponseAsync(string userQuestion)
    {
        string? ragContext;
        try
        {
            ragContext = await GetCurriculumContextAsync();
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to load the curriculum context from Postgres. Key: {Key}", paramKey);
            return NoAccessMessage;
        }

        if (string.IsNullOrWhiteSpace(ragContext))
        {
            logger.LogWarning("Curriculum context not found in Postgres. Key: {Key}", paramKey);
            return NoAccessMessage;
        }

        try
        {
            // Strongly-typed payload for Native AOT
            var payload = new GeminiRequest
            {
                SystemInstruction = new GeminiSystemInstruction
                {
                    Parts = [new GeminiPart { Text = systemInstruction }]
                },
                Contents =
                [
                    new GeminiContent
                    {
                        Role = "user",
                        Parts = [new GeminiPart { Text = $"<rag_context>\n{ragContext}\n</rag_context>\n\n<user_input>\n{userQuestion}\n</user_input>" }]
                    }
                ]
            };

            // Serialization via Source Generator
            var jsonPayload = JsonSerializer.Serialize(payload, AppJsonContext.Default.GeminiRequest);

            // Tries the primary model; on failure, falls back to the secondary model
            var primaryResult = await TryGenerateResponseAsync(geminiUrl, jsonPayload);
            if (!string.IsNullOrWhiteSpace(primaryResult))
            {
                logger.LogInformation("Answer generated by the primary Gemini model: {Model}.", ExtractModelName(geminiUrl));
                return primaryResult!;
            }

            logger.LogWarning("Primary model ({Model}) unavailable, trying the fallback model ({FallbackModel}).",
                ExtractModelName(geminiUrl), ExtractModelName(geminiFallbackUrl));
            var fallbackResult = await TryGenerateResponseAsync(geminiFallbackUrl, jsonPayload);

            if (!string.IsNullOrWhiteSpace(fallbackResult))
            {
                logger.LogInformation("Answer generated by the fallback Gemini model: {Model}.", ExtractModelName(geminiFallbackUrl));
                return fallbackResult!;
            }

            logger.LogError("Failed to get an answer from both the primary ({Model}) and fallback ({FallbackModel}) models.",
                ExtractModelName(geminiUrl), ExtractModelName(geminiFallbackUrl));
            return "Desculpe, estou com dificuldades para acessar meu cérebro de IA agora. Tente novamente em instantes.";
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Critical failure while communicating with the Gemini service.");
            return "Ocorreu um erro no meu sistema de processamento de linguagem.";
        }
    }

    /// <summary>
    /// Builds the RAG context from the curriculum stored in Postgres, using an
    /// in-memory cache (15 minutes TTL) to avoid hitting the database repeatedly.
    /// </summary>
    /// <returns>
    /// The curriculum context, or <see langword="null"/> when the parameter does
    /// not exist. Throws when the database is unreachable.
    /// </returns>
    private async Task<string?> GetCurriculumContextAsync()
    {
        string cacheKey = $"iris:context:{paramKey}";

        if (cache.TryGetValue(cacheKey, out string? cachedContext) && !string.IsNullOrWhiteSpace(cachedContext))
        {
            return cachedContext;
        }

        Parameter? parameter = await parameterRepository.GetByKeyAsync(paramKey);
        if (parameter is null || string.IsNullOrWhiteSpace(parameter.ParamValue))
        {
            return null;
        }

        cache.Set(cacheKey, parameter.ParamValue, ContextCacheTtl);
        return parameter.ParamValue;
    }

    /// <summary>
    /// Calls the Gemini API for the given model URL and payload, returning the
    /// generated text. Non-successful responses and HTTP failures yield
    /// <see langword="null"/> (already logged).
    /// </summary>
    /// <param name="url">The full generateContent URL of the model.</param>
    /// <param name="jsonPayload">The serialized request payload.</param>
    /// <returns>The generated text, or <see langword="null"/> on failure.</returns>
    private async Task<string?> TryGenerateResponseAsync(string url, string jsonPayload)
    {
        var urlWithKey = $"{url}?key={apiKey}";
        var httpContent = new StringContent(jsonPayload, Encoding.UTF8, "application/json");

        try
        {
            using var httpResponse = await httpClient.PostAsync(urlWithKey, httpContent);

            if (!httpResponse.IsSuccessStatusCode)
            {
                var errorDetails = await httpResponse.Content.ReadAsStringAsync();
                logger.LogError("Error calling the Gemini API. URL: {Url}. Status: {Status}. Details: {Error}", url, httpResponse.StatusCode, errorDetails);
                return null;
            }

            // Deserialization via Source Generator
            var jsonResponse = await httpResponse.Content.ReadAsStringAsync();
            var geminiResult = JsonSerializer.Deserialize(jsonResponse, AppJsonContext.Default.GeminiResponse);
            var responseText = geminiResult?.Candidates?[0].Content?.Parts?[0].Text;

            return responseText?.Trim() ?? "Não consegui formular uma resposta adequada. Pode perguntar de outra forma?";
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "HTTP request to the Gemini API failed. URL: {Url}", url);
            return null;
        }
    }

    /// <summary>
    /// Extracts the model name from a generateContent URL.
    /// </summary>
    /// <param name="url">The model URL containing /models/[name]:generateContent.</param>
    /// <returns>The model name, or the full URL when it cannot be parsed.</returns>
    private static string ExtractModelName(string url)
    {
        var marker = "/models/";
        var index = url.IndexOf(marker, StringComparison.Ordinal);
        if (index < 0) return url;

        var segment = url[(index + marker.Length)..];
        var end = segment.IndexOf(":generateContent", StringComparison.Ordinal);
        return end > 0 ? segment[..end] : segment;
    }
}

// ==============================================================================
// Request DTOs (Gemini API)
// ==============================================================================
/// <summary>
/// Payload sent to the Gemini generateContent API.
/// </summary>
public class GeminiRequest
{
    [JsonPropertyName("systemInstruction")]
    public GeminiSystemInstruction? SystemInstruction { get; set; }

    [JsonPropertyName("contents")]
    public GeminiContent[]? Contents { get; set; }
}

/// <summary>
/// System-level instruction block of a Gemini request.
/// </summary>
public class GeminiSystemInstruction
{
    [JsonPropertyName("parts")]
    public GeminiPart[]? Parts { get; set; }
}

/// <summary>
/// A conversational turn sent to the Gemini API.
/// </summary>
public class GeminiContent
{
    [JsonPropertyName("role")]
    public string Role { get; set; } = "user";

    [JsonPropertyName("parts")]
    public GeminiPart[]? Parts { get; set; }
}

/// <summary>
/// A single text part of a Gemini message.
/// </summary>
public class GeminiPart
{
    [JsonPropertyName("text")]
    public string? Text { get; set; }
}

// ==============================================================================
// Response DTOs (Gemini API)
// ==============================================================================
/// <summary>
/// Response received from the Gemini generateContent API.
/// </summary>
public class GeminiResponse
{
    [JsonPropertyName("candidates")]
    public Candidate[]? Candidates { get; set; }
}

/// <summary>
/// A candidate answer returned by the Gemini API.
/// </summary>
public class Candidate
{
    [JsonPropertyName("content")]
    public ContentNode? Content { get; set; }
}

/// <summary>
/// Content node of a Gemini candidate.
/// </summary>
public class ContentNode
{
    [JsonPropertyName("parts")]
    public PartNode[]? Parts { get; set; }
}

/// <summary>
/// A text part of a Gemini candidate's content.
/// </summary>
public class PartNode
{
    [JsonPropertyName("text")]
    public string? Text { get; set; }
}