-- =====================================================================
-- Portal IRibeiro - Database schema (English naming)
--
-- Drop + create to be applied in local and production environments.
-- Consolidates migrations 001 (visits) and 002 (rename to English).
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS portal;

DROP TABLE IF EXISTS portal.visits;
DROP TABLE IF EXISTS portal.projects;
DROP TABLE IF EXISTS portal.chat_history;

-- ---------------------------------------------------------------------
-- Projects
-- ---------------------------------------------------------------------
CREATE TABLE portal.projects (
    id serial4 NOT NULL,
    title varchar(150) NOT NULL,
    description text NOT NULL,
    technologies varchar[] NOT NULL,
    image_url varchar(255) NULL,
    github_url varchar(255) NULL,
    demo_url varchar(255) NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
    is_active bool DEFAULT true NULL,
    CONSTRAINT projects_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_projects_active ON portal.projects USING btree (created_at DESC) WHERE (is_active = true);

-- ---------------------------------------------------------------------
-- Chat history
-- ---------------------------------------------------------------------
CREATE TABLE portal.chat_history (
    id bigserial NOT NULL,
    session_id uuid NOT NULL,
    user_question text NOT NULL,
    ai_response text NOT NULL,
    interaction_date timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
    CONSTRAINT chat_history_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_chat_history_session ON portal.chat_history USING btree (session_id);

-- ---------------------------------------------------------------------
-- Visits
-- ---------------------------------------------------------------------
CREATE TABLE portal.visits (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Unique identifier of the visit record.
    ip_address varchar(45) NULL, -- IP address of the visitor, supporting IPv4 and IPv6.
    country varchar(100) NULL, -- Country estimated from the visitor IP address.
    city varchar(100) NULL, -- City estimated from the visitor IP address.
    region varchar(100) NULL, -- Region or state estimated from the visitor IP address.
    page varchar(200) NULL, -- Portal page accessed by the visitor.
    user_agent text NULL, -- HTTP User-Agent reported by the visitor client.
    accessed_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL, -- UTC timestamp when the visit was recorded.
    referer text NULL, -- HTTP Referer indicating the page or website that originated the navigation.
    visit_type varchar(30) NULL, -- Classification of the visit, such as human, crawler, social_crawler, bot, or unknown.
    bot_name varchar(100) NULL, -- Identified name of the crawler or bot, when applicable.
    CONSTRAINT visits_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_visits_accessed_at ON portal.visits USING btree (accessed_at DESC);
CREATE INDEX idx_visits_ip_address_accessed_at ON portal.visits USING btree (ip_address, accessed_at DESC);
CREATE INDEX idx_visits_visit_type_accessed_at ON portal.visits USING btree (visit_type, accessed_at DESC);

COMMENT ON TABLE portal.visits IS 'Stores visitor telemetry collected by the portal.';
